### ISSUE TITLE
[BUG] Organizations endpoint returns inconsistent lists or pages with the same request

### ISSUE THREAD

**Issue by codycooperross** [ror-community/ror-roadmap#240] opened 2024-05-06 14:22 UTC
**Version**
The version of the ROR schema and/or API you are using: v1, v2, or unknown.

v1

**Describe the bug**

The organizations endpoint appears to return two different but internally consistent lists per page. If you refresh the following a few times, the results seem to oscillate between two lists: https://api.ror.org/organizations?filter=country.country_code:CL The same is true for every succeeding page: https://api.ror.org/organizations?filter=country.country_code:CL&page=2

**To Reproduce**
1. Make a https://api.ror.org/organizations request and refresh a few times. 

**Expected behavior**

While paging, each page returns a consistent list of results. 

**Screenshots**

**Device information:**
 - Device type: [e.g. desktop, tablet, phone]

**Additional context**

A user noticed this inconsistency while using the DataCite GraphQL API for organizations to retrieve a list of organizations with country code CL. Because the pages seem to switch around, they were retrieving duplicate results.

**Comment by amandafrench** [comment] 2024-05-07 12:33
Oh, interesting. Thanks for reporting, @codycooperross. I've reproduced this in both Firefox and Chrome on my Mac. The count of organizations stays the same, so I'm assuming for the moment at least that the result list is the same, but the first returned record does change upon every request.

**Comment by amandafrench** [comment] 2024-05-07 12:50
Have reproduced with this filter in v2 as well, and it also occurs with the `types` filter and without any filter at all (e.g., https://api.ror.org/v2/organizations).

**Comment by lizkrznarich** [comment] 2024-07-17 17:38
This is likely due to inconsistent document ordering between replicas and no explicit ordering in applied in the ElasticSearch request.

**Comment by ashwinisukale** [comment] 2024-09-23 09:44
Closing as fix is merged to dev branch

**Closed** 2024-09-23 09:44 UTC
Labels: bug
